package service.impl;

import org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

// boilerplate code autogenerated by intellij
class MenuServiceImplTest {

    @Test
    void findVegetarianFood() {
        System.out.println("Hello test");
    }

    @Test
    void findFoodByType() {
    }

    @Test
    void findFoodStartingWithName() {
    }

    @Test
    void findFoodCheaperWithCalories() {
    }

    @Test
    void testFindFoodStartingWithName() {
    }

    @Test
    void findFoodContaining() {
    }

    @Test
    void findFoodExcludingAll() {
    }
}